In [1]:
import numpy as np
import matplotlib.pyplot as plt  
import tensorflow as tf


# Custom Stuff with tf 

Following [this](https://www.tensorflow.org/tutorials/customization/basics) tutorial.  



## Tensors and Operations 

### Tensors 
+ ndarray similar to np arrays 
+ have a dtype and shape  
+ can resides in acellerator memory (like GPU)  
+ operations exist that consume and produce tensors (tf.add, tf.matmul, etc.) 


In [16]:
print(tf.add(1, 2))
print(tf.add([1, 2], [4, 3]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([5 5], shape=(2,), dtype=int32)


Differences between np arrays and tf arrays 
+ backed by accelerator memory (GPU, TPU) 
+ immutable 

In [36]:
t = tf.convert_to_tensor([1, 3])
try: 
    t[1] = 2
    print(t)
except:
    print('Assignment cant happen')

Assignment cant happen


### Datasets 

The dataset API builds pipelines for feeding data to your model.  It is used to build performant, complex input pipelines from simple, re-usable pieces that will feed your model's training or evaluation loops.  


#### Creating a source dataset 

`Dataset.from_tensors` , `Dataset.from_tensor_slices`, `TextLineDataset`, `TFRecordDataset`.  
See [dataset guide](https://www.tensorflow.org/guide/datasets#reading_input_data) for more info 

In [49]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6, 7, 8, 9])

import tempfile 

_, filename = tempfile.mkstemp()

with open(filename, 'w') as f: 
    f.write("""Line 1 
    Line 2
    Line 3""")
    
ds_file = tf.data.TextLineDataset(filename)

#### Apply transformations 

Use `map`, `batch`, `shuffle` to apply transforms 

In [50]:
ds_tensors = ds_tensors.map(tf.square).shuffle(3).batch(3)

ds_file = ds_file.batch(2) 

#### Iterate 

In [52]:
print("Elements of ds_tensors: ")
for x in ds_tensors: 
    print(x)

print("\n\nElements of ds_file")
for x in ds_file: 
    print(x)

Elements of ds_tensors: 
tf.Tensor([ 4 16  1], shape=(3,), dtype=int32)
tf.Tensor([ 9 36 25], shape=(3,), dtype=int32)
tf.Tensor([64 49 81], shape=(3,), dtype=int32)


Elements of ds_file
tf.Tensor([b'Line 1 ' b'    Line 2'], shape=(2,), dtype=string)
tf.Tensor([b'    Line 3'], shape=(1,), dtype=string)


## Custom layers 

## Variables 

Tensors are immutable stateless objects.  `x + 2` does not mutate the state of x.  You need to do `x = x + 2`.  

A `tf.Variable` object stores a value and implicitly reads from this stored value.  There are operations that manipulate the value stored in a tf variable.  

In [5]:
v = tf.Variable(1.0)
print(v)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.0>


In [8]:
v.assign(3.0)
v

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [12]:
v + 1
v # remained unchanged 

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>

In [13]:
v.assign(tf.square(v))
print(v.numpy())

9.0


Computations using `tf.Variable` are automatically traced when computing gradients.  For variables that represent embeddings, Tensorflow will do sparse updates by default, which are more computation and memory efficient.  

## Example using linear model

